apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  selector:
    app.kubernetes.io/name: qbittorrent
  type: ClusterIP
  ports:
    - name: webui
      port: 8081
      targetPort: webui
      protocol: TCP
